name: 📦 Build Genius Invokation
run-name: ${{ github.actor }} is building Genius Invokation

on:
  push:
    branches: [xqm32/pyci]

jobs:
  Build-Core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: |
          bun install
          bun run build:prod
      - uses: actions/upload-artifact@v4
        with:
          name: cbinding-source
          path: packages/cbinding
      - uses: actions/upload-artifact@v4
        with:
          name: pybinding-source
          path: packages/pybinding

  Build-C:
    needs: Build-Core
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            build_type: Release
            arch: x86_64
          - os: windows-2022
            build_type: Release
            arch: x86_64
          - os: macos-15
            build_type: Release
            arch: x86_64
          - os: macos-15
            build_type: Release
            arch: arm64
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cbinding-source
          path: cbinding
      - uses: lukka/get-cmake@v3.31.0
      - if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/cache@v4
        with:
          path: cbinding/build
          key: ${{ runner.os }}-${{ matrix.arch }}-build
      - run: >
          cmake
          -B cbinding/build
          -S cbinding
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_APPLE_SILICON_PROCESSOR=${{ matrix.arch }}
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}
      - run: >
          cmake
          --build cbinding/build
          --config ${{ matrix.build_type }}
      - run: >
          cmake
          --install cbinding/build
          --config ${{ matrix.build_type }}
          --prefix cbinding/install
      - uses: actions/upload-artifact@v4
        with:
          name: cbinding-library-${{ runner.os }}-${{ matrix.arch }}
          path: cbinding/install

  Build-Python:
    needs: Build-C
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pybinding-source
          path: pybinding
      - uses: actions/download-artifact@v4
        with:
          pattern: cbinding-library-*
          path: cbinding
      - uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - run: |
          uv run pybinding/scripts/build.py
      - uses: actions/upload-artifact@v4
        with:
          name: pybinding-dist
          path: pybinding/dist/*.whl
      - if: startsWith(github.ref, 'refs/tags/')
        run: |
          pushd pybinding
          uv publish
          popd
